package com.epam.hotel.access;

import java.util.HashMap;
import java.util.Map;

import static com.epam.hotel.util.constant.ActionConstant.*;

class AccessMap {

    private static final String SLASH_CONSTANT = "/";

    protected static Map<String, Boolean> accessClientMap = new HashMap<>();
    protected static Map<String, Boolean> accessAdminMap = new HashMap<>();
    protected static Map<String, Boolean> accessGuestMap = new HashMap<>();

    static {
        accessClientMap.put(SLASH_CONSTANT, true);
        accessClientMap.put(INDEX_JSP, true);
        accessClientMap.put(LOGIN_JSP, true);
        accessClientMap.put(CABINET_JSP, true);
        accessClientMap.put(REGISTRATION_JSP, true);
        accessClientMap.put(SHOW_ROOMS_JSP, true);
        accessClientMap.put(SHOW_ROOMS_BY_CLASS_JSP, true);
        accessClientMap.put(SHOW_PERSON_ADMIN_LIST_JSP, false);
        accessClientMap.put(EDIT_PERSON_JSP, false);
        accessClientMap.put(EDIT_ROOM_JSP, false);
        accessClientMap.put(CREATE_ITEM_JSP, true);
        accessClientMap.put(SHOW_MY_ORDERS_JSP, true);
        accessClientMap.put(ERROR_JSP, true);
        accessClientMap.put(SHOW_ROOM_ADMIN_LIST_JSP, false);
        accessClientMap.put(SHOW_ROOM_CLASS_ADMIN_LIST_JSP, false);
        accessClientMap.put(SHOW_ORDER_ADMIN_LIST_JSP, false);
        accessClientMap.put(SHOW_ORDER_STATUS_ADMIN_LIST_JSP, false);
        accessClientMap.put(SHOW_ORDER_ROOM_DETAIL_JSP, true);
        accessClientMap.put(EDIT_ORDER_JSP, false);
        accessClientMap.put(EDIT_ORDER_ROOM_DETAIL_JSP, false);
        accessClientMap.put(SHOW_FACILITY_PACKAGE_ADMIN_LIST_JSP, false);
        accessClientMap.put(SHOW_FACILITY_ADMIN_LIST_JSP, false);
        accessClientMap.put(SHOW_CART_JSP, true);
        accessClientMap.put(PAY_ORDER_JSP, true);
        accessClientMap.put(PAYMENT_JSP, true);
        accessClientMap.put(LANGUAGE_JSP, false);
        accessClientMap.put(ADMIN_RIGHT_PANEL_JSP, false);
        accessClientMap.put(CREATE_FACILITY_JSP, false);
        accessClientMap.put(CREATE_FACILITY_PACKAGE_JSP, false);
        accessClientMap.put(CREATE_ORDER_STATUS_JSP, false);
        accessClientMap.put(CREATE_PERSON_JSP, false);
        accessClientMap.put(CREATE_ROOM_JSP, false);
        accessClientMap.put(CREATE_ROOM_CLASS_JSP, false);
        accessClientMap.put(EDIT_FACILITY_JSP, false);
        accessClientMap.put(EDIT_FACILITY_PACKAGE_JSP, false);
        accessClientMap.put(EDIT_ORDER_STATUS_JSP, false);
        accessClientMap.put(EDIT_ROOM_CLASS_JSP, false);
        accessClientMap.put(HEADER_JSP, true);
        accessClientMap.put(SHOW_ROOM_IMAGES_JSP, true);
        accessClientMap.put(STYLE_JSP, true);
        accessClientMap.put(UPLOAD_IMAGE_JSP, false);

        accessAdminMap.put(SLASH_CONSTANT, true);
        accessAdminMap.put(INDEX_JSP, true);
        accessAdminMap.put(CABINET_JSP, true);
        accessAdminMap.put(LOGIN_JSP, true);
        accessAdminMap.put(REGISTRATION_JSP, true);
        accessAdminMap.put(SHOW_ROOMS_JSP, true);
        accessAdminMap.put(SHOW_ROOMS_BY_CLASS_JSP, true);
        accessAdminMap.put(SHOW_PERSON_ADMIN_LIST_JSP, true);
        accessAdminMap.put(EDIT_PERSON_JSP, true);
        accessAdminMap.put(EDIT_ROOM_JSP, true);
        accessAdminMap.put(CREATE_ITEM_JSP, true);
        accessAdminMap.put(SHOW_MY_ORDERS_JSP, true);
        accessAdminMap.put(ERROR_JSP, true);
        accessAdminMap.put(SHOW_ROOM_ADMIN_LIST_JSP, true);
        accessAdminMap.put(SHOW_ROOM_CLASS_ADMIN_LIST_JSP, true);
        accessAdminMap.put(SHOW_ORDER_ADMIN_LIST_JSP, true);
        accessAdminMap.put(SHOW_ORDER_STATUS_ADMIN_LIST_JSP, true);
        accessAdminMap.put(SHOW_ORDER_ROOM_DETAIL_JSP, true);
        accessAdminMap.put(EDIT_ORDER_JSP, true);
        accessAdminMap.put(EDIT_ORDER_ROOM_DETAIL_JSP, true);
        accessAdminMap.put(SHOW_FACILITY_PACKAGE_ADMIN_LIST_JSP, true);
        accessAdminMap.put(SHOW_FACILITY_ADMIN_LIST_JSP, true);
        accessAdminMap.put(SHOW_CART_JSP, true);
        accessAdminMap.put(PAY_ORDER_JSP, true);
        accessAdminMap.put(PAYMENT_JSP, true);
        accessAdminMap.put(LANGUAGE_JSP, true);
        accessAdminMap.put(ADMIN_RIGHT_PANEL_JSP, true);
        accessAdminMap.put(CREATE_FACILITY_JSP, true);
        accessAdminMap.put(CREATE_FACILITY_PACKAGE_JSP, true);
        accessAdminMap.put(CREATE_ORDER_STATUS_JSP, true);
        accessAdminMap.put(CREATE_PERSON_JSP, true);
        accessAdminMap.put(CREATE_ROOM_JSP, true);
        accessAdminMap.put(CREATE_ROOM_CLASS_JSP, true);
        accessAdminMap.put(EDIT_FACILITY_JSP, true);
        accessAdminMap.put(EDIT_FACILITY_PACKAGE_JSP, true);
        accessAdminMap.put(EDIT_ORDER_STATUS_JSP, true);
        accessAdminMap.put(EDIT_ROOM_CLASS_JSP, true);
        accessAdminMap.put(HEADER_JSP, true);
        accessAdminMap.put(SHOW_ROOM_IMAGES_JSP, true);
        accessAdminMap.put(STYLE_JSP, true);
        accessAdminMap.put(UPLOAD_IMAGE_JSP, true);

        accessGuestMap.put(SLASH_CONSTANT, true);
        accessGuestMap.put(INDEX_JSP, true);
        accessGuestMap.put(LOGIN_JSP, true);
        accessGuestMap.put(CABINET_JSP, false);
        accessGuestMap.put(REGISTRATION_JSP, true);
        accessGuestMap.put(SHOW_ROOMS_JSP, true);
        accessGuestMap.put(SHOW_ROOMS_BY_CLASS_JSP, true);
        accessGuestMap.put(SHOW_PERSON_ADMIN_LIST_JSP, false);
        accessGuestMap.put(EDIT_PERSON_JSP, false);
        accessGuestMap.put(EDIT_ROOM_JSP, false);
        accessGuestMap.put(CREATE_ITEM_JSP, false);
        accessGuestMap.put(SHOW_MY_ORDERS_JSP, false);
        accessGuestMap.put(ERROR_JSP, true);
        accessGuestMap.put(SHOW_ROOM_ADMIN_LIST_JSP, false);
        accessGuestMap.put(SHOW_ROOM_CLASS_ADMIN_LIST_JSP, false);
        accessGuestMap.put(SHOW_ORDER_ADMIN_LIST_JSP, false);
        accessGuestMap.put(SHOW_ORDER_STATUS_ADMIN_LIST_JSP, false);
        accessGuestMap.put(SHOW_ORDER_ROOM_DETAIL_JSP, false);
        accessGuestMap.put(EDIT_ORDER_JSP, false);
        accessGuestMap.put(EDIT_ORDER_ROOM_DETAIL_JSP, false);
        accessGuestMap.put(SHOW_FACILITY_PACKAGE_ADMIN_LIST_JSP, false);
        accessGuestMap.put(SHOW_FACILITY_ADMIN_LIST_JSP, false);
        accessGuestMap.put(SHOW_CART_JSP, false);
        accessGuestMap.put(PAY_ORDER_JSP, false);
        accessGuestMap.put(PAYMENT_JSP, false);
        accessGuestMap.put(LANGUAGE_JSP, false);
        accessGuestMap.put(ADMIN_RIGHT_PANEL_JSP, false);
        accessGuestMap.put(CREATE_FACILITY_JSP, false);
        accessGuestMap.put(CREATE_FACILITY_PACKAGE_JSP, false);
        accessGuestMap.put(CREATE_ORDER_STATUS_JSP, false);
        accessGuestMap.put(CREATE_PERSON_JSP, false);
        accessGuestMap.put(CREATE_ROOM_JSP, false);
        accessGuestMap.put(CREATE_ROOM_CLASS_JSP, false);
        accessGuestMap.put(EDIT_FACILITY_JSP, false);
        accessGuestMap.put(EDIT_FACILITY_PACKAGE_JSP, false);
        accessGuestMap.put(EDIT_ORDER_STATUS_JSP, false);
        accessGuestMap.put(EDIT_ROOM_CLASS_JSP, false);
        accessGuestMap.put(HEADER_JSP, false);
        accessGuestMap.put(SHOW_ROOM_IMAGES_JSP, true);
        accessGuestMap.put(STYLE_JSP, false);
        accessGuestMap.put(UPLOAD_IMAGE_JSP, false);
    }
}