package com.epam.hotel.dao.impl;

public class DAOConstant {
    public static final String DATE_PATTERN = "yyyy-MM-dd";
    protected static final String ID = "id";
    protected static final String NAME = "name";
    protected static final String PRICE = "price";
    protected static final String DESCRIPTION = "description";
    protected static final String FACILITY_PACKAGE_ID = "facility_package_id";
    protected static final String ORDER_ID = "order_id";
    protected static final String STATUS_ID = "status_id";
    protected static final String PERSON_ID = "person_id";
    protected static final String EN = "en";
    protected static final String RU = "ru";
    protected static final String DATE = "date";
    protected static final String FIRST_NAME = "first_name";
    protected static final String LAST_NAME = "last_name";
    protected static final String BIRTHDAY = "birthday";
    protected static final String PHONE = "phone";
    protected static final String EMAIL = "email";
    protected static final String IIN = "iin";
    protected static final String PASSWORD = "password";
    protected static final String IS_ADMIN = "is_admin";
    protected static final String IS_BAN = "is_ban";
    protected static final String ROOM_NUMBER = "room_number";
    protected static final String CAPACITY = "capacity";
    protected static final String ROOM_CLASS_ID = "room_class_id";
    protected static final String ROOM_CLASS_EN = "room_class_en";
    protected static final String ROOM_CLASS_RU = "room_class_ru";
    protected static final String AVAILABILITY = "availability";
    protected static final String ROOM_ID = "room_id";
    protected static final String IMAGE = "image";
    protected static final String ORDER_FACILITY_DETAIL_ID = "order_facility_detail_id";
    protected static final String ORDER_MAIN_ID = "order_main_id";
    protected static final String START_DATE = "start_date";
    protected static final String END_DATE = "end_date";
    protected static final String FACILITY_PACKAGE_NAME = "facility_package_name";
    protected static final String PACKAGE_ID = "package_id";
    protected static final String FACILITY_ID = "facility_id";
    protected static final String FACILITY_NAME = "facility_name";
    protected static final String FACILITY_DESCRIPTION = "facility_description";
    protected static final String FACILITY_PRICE = "facility_price";
    protected static final String PACKAGE_ID_RELATION = "package_id_relation";
    protected static final String FACILITY_ID_RELATION = "facility_id_relation";
}