package com.epam.hotel.action.impl;

public class ActionConstant {

    public static final String INDEX_URL = "/index.jsp";
    protected static final String LOGIN_URL = "/login.jsp";
    protected static final String REGISTRATION_URL = "/registration.jsp";
    protected static final String SHOW_ROOMS_URL = "/show_rooms.jsp";
    protected static final String SHOW_ROOMS_BY_CLASS_URL = "/show_rooms_by_class.jsp";
    protected static final String CABINET_URL = "/cabinet.jsp";
    protected static final String SHOW_PERSON_ADMIN_LIST_URL = "/show_person_admin_list.jsp";
    protected static final String EDIT_PERSON_URL = "/edit_person.jsp";
    protected static final String EDIT_ROOM_URL = "/edit_room.jsp";
    protected static final String CREATE_ITEM_URL = "/create_item.jsp";
    protected static final String SHOW_MY_ORDERS_URL = "/show_my_orders.jsp";
    public static final String UPLOAD_IMAGE_URL = "/upload_image.jsp";
    public static final String ERROR_URL = "/error.jsp";
    public static final String SHOW_ROOM_ADMIN_LIST_URL = "/show_room_admin_list.jsp";
    public static final String SHOW_ORDER_ADMIN_LIST_URL = "/show_order_admin_list.jsp";
    public static final String SHOW_ORDER_ROOM_DETAIL_URL = "/show_order_room_detail.jsp";
    public static final String EDIT_ORDER_URL = "/edit_order.jsp";
    public static final String EDIT_ORDER_ROOM_DETAIL_URL = "/edit_order_room_detail.jsp";
    public static final String SHOW_FACILITY_PACKAGE_ADMIN_LIST_URL = "/show_facility_package_admin_list.jsp";
    public static final String SHOW_FACILITY_ADMIN_LIST_URL = "/show_facility_admin_list.jsp";
    public static final String SHOW_CART_URL = "/show_cart.jsp";
    public static final String PAY_ORDER_URL = "/pay_order.jsp";
    public static final String PAYMENT_URL = "/payment.jsp";
    public static final String LANGUAGE_URL = "/language.jsp";

    public static final int DELUXE = 1;
    public static final int SUITE = 2;
    public static final int STANDARD = 3;

    public static final int NEW = 1;
    public static final int IN_PROGRESS = 2;
    public static final int DONE = 3;
    public static final int CANCELLED = 4;
    public static final int DENIAL = 5;
    public static final int PAID = 6;

    public static final String ROLE = "role";
    public static final String MESSAGE = "message";
    public static final String PERSON = "person";
    public static final String EMPTY_STRING = "";
    protected static final int ZERO = 0;
    protected static final String ORDER_MAIN_ID = "order_main_id";
    protected static final String FACILITY_NAME = "facility_name";
    protected static final String FACILITY_DESCRIPTION = "facility_description";
    protected static final String FACILITY_PRICE = "facility_price";
    protected static final String ROOM_ID = "room_id";
    protected static final String DETAIL_ID = "detail_id";
    protected static final String START_DATE = "start_date";
    protected static final String END_DATE = "end_date";
    protected static final String CART = "cart";
    protected static final String FACILITIES = "facilities";
    protected static final String FIRST_NAME = "first_name";
    protected static final String LAST_NAME = "last_name";
    protected static final String BIRTHDAY = "birthday";
    protected static final String PHONE = "phone";
    protected static final String EMAIL = "email";
    protected static final String IIN = "iin";
    protected static final String PASSWORD = "password";
    protected static final String ADMIN = "admin";
    protected static final String BAN = "ban";
    protected static final String ROOM_NUMBER = "room_number";
    protected static final String CAPACITY = "capacity";
    protected static final String ROOM_CLASS = "room_class";
    protected static final String PRICE = "price";
    protected static final String AVAILABILITY = "availability";
    protected static final String FACILITY_ID = "facility_id";
    protected static final String ORDER_DETAIL_ID = "order_detail_id";
    protected static final String ORDER_ROOM_DETAIL_ID = "order_room_detail_id";
    protected static final String PERSON_ID = "person_id";
    protected static final String ID = "id";
    protected static final String IMAGE_ID = "image_id";
    protected static final String STATUS = "status";
    protected static final String DATE = "date";
    protected static final String FACILITY_PACKAGE_ID = "facility_package_id";
    protected static final String CARD_NUMBER = "card_number";
    protected static final String ROOM_LIST = "room_list";
    protected static final String NULL = "null";
    protected static final String ROOM_ID_FOR_UPLOAD = "room_id_for_upload";
    protected static final String ROOM_IMAGE_ID_RADIO = "room_image_id_radio";
    protected static final String IMAGE_BYTES = "image_bytes";
    protected static final String DISCOUNT = "discount";
    protected static final String LOCALE = "locale";
    protected static final String LANGUAGE_ID = "language_id";
}